### ISSUE TITLE
Development build instructions using conda on MacOS giving exception

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#765]
I was just testing a fresh development build for Mac OS using conda (the instructions in the [readme](https://github.com/HEXRD/hexrdgui#mac-os)), and I am getting an error when trying to fire up the GUI (see below).  @psavery is this related to #763 or [#181 on hexrd](https://github.com/HEXRD/hexrd/pull/181)?  The Fabio tag 0.11 seems to be causing an issue; I asked for >=0.11, and the desired release on PyPI is indeed [0.11](https://pypi.org/project/fabio/) 
```
(hexrdgui) calhoun:~ bernier2$ hexrdgui
Traceback (most recent call last):
  File "/Users/bernier2/miniconda3/envs/hexrdgui/lib/python3.8/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/Users/bernier2/miniconda3/envs/hexrdgui/lib/python3.8/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/bernier2/miniconda3/envs/hexrdgui/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (fabio 0.11.0a1 (/Users/bernier2/miniconda3/envs/hexrdgui/lib/python3.8/site-packages), Requirement.parse('fabio>=0.11'), {'hexrdgui'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bernier2/miniconda3/envs/hexrdgui/bin/hexrdgui", line 33, in <module>
    sys.exit(load_entry_point('hexrdgui', 'gui_scripts', 'hexrdgui')())
  File "/Users/bernier2/miniconda3/envs/hexrdgui/bin/hexrdgui", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/bernier2/miniconda3/envs/hexrdgui/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/bernier2/miniconda3/envs/hexrdgui/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/bernier2/Documents/GitHub/hexrd/hexrd/__init__.py", line 3, in <module>
    from pkg_resources import DistributionNotFound, get_distribution
  File "/Users/bernier2/miniconda3/envs/hexrdgui/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/Users/bernier2/miniconda3/envs/hexrdgui/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/Users/bernier2/miniconda3/envs/hexrdgui/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/bernier2/miniconda3/envs/hexrdgui/lib/python3.8/site-packages/pkg_resources/__init__.py", line 569, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/bernier2/miniconda3/envs/hexrdgui/lib/python3.8/site-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/bernier2/miniconda3/envs/hexrdgui/lib/python3.8/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'fabio>=0.11' distribution was not found and is required by hexrdgui
(hexrdgui) calhoun:~ bernier2$ 
```

**Comment by psavery** [comment]
I was able to reproduce this with both of these methods:
```python
conda install -c HEXRD -c anaconda -c conda-forge hexrdgui
pip install --no-deps -U -e hexrd
CONDA_BUILD=1 pip install --no-deps -U -e hexrdgui
```

```python
conda install -c hexrd/label/hexrd-prerelease -c hexrd/label/hexrdgui-prerelease -c HEXRD -c anaconda -c conda-forge hexrdgui
pip install --no-deps -U -e hexrd
CONDA_BUILD=1 pip install --no-deps -U -e hexrdgui
```

It might be caused by #181, but I'm surprised that the error is with fabio. I'll look into it a little more...

**Comment by psavery** [comment]
I think I was able to get it working by moving [this fabio](https://github.com/HEXRD/hexrdgui/blob/da77862690d941fd77126e851632b767c3f179bd/setup.py#L9) into [this block](https://github.com/HEXRD/hexrdgui/blob/da77862690d941fd77126e851632b767c3f179bd/setup.py#L20), and moving [this appdirs](https://github.com/HEXRD/hexrd/blob/09e793082a73272dc8626fdc4c4c0d46e926f11a/setup.py#L10) into [this block](https://github.com/HEXRD/hexrd/blob/09e793082a73272dc8626fdc4c4c0d46e926f11a/setup.py#L29), and using `CONDA_BUILD=1` for the hexrd install as well, so this:

```bash
conda install -c HEXRD -c anaconda -c conda-forge hexrdgui
CONDA_BUILD=1 pip install --no-deps -U -e hexrd
CONDA_BUILD=1 pip install --no-deps -U -e hexrdgui
```

I'm gonna test this more a little later. Full patch files are below.

[hexrdgui.patch.txt](https://github.com/HEXRD/hexrdgui/files/6031989/hexrdgui.patch.txt)
[hexrd.patch.txt](https://github.com/HEXRD/hexrdgui/files/6031990/hexrd.patch.txt)

**Comment by psavery** [comment]
@cjh1 It looks like because fabio is still in our conda channel at https://anaconda.org/hexrd, we are grabbing our fabio instead of the one on conda forge (since our channel comes first). Should we remove our fabio?

**Comment by psavery** [comment]
So, looking into it deeper, it looks to me that the `pkg_resources.DistributionNotFound` errors were fixed via those patch files in https://github.com/HEXRD/hexrdgui/issues/765#issuecomment-784538639.

However, it looks like hexrd/hexrd#181 is still causing a problem for us with the conda setup. The problem is that we install numpy from anaconda, but when you use pyproject.toml, `python setup.py develop` gets ran in a virtual environment created by pip, where it installed its own build dependencies via `pip install`, and it `pip install`'s numpy - a different numpy.

So it is being built with one version of numpy (from PyPI), and it is trying to use a different version of numpy at runtime (from Anaconda). This is causing an error `ImportError: numpy.core.multiarray failed to import`.

It looks like we can circumvent this issue, though, by passing to pip `--no-build-isolation`. This prevents pip from installing its own numpy to use for the build. I can add that and it fixes the problems.

I'll update the README to reflect this.

**Comment by psavery** [comment]
@joelvbernier @cjh1 All of the issues I encountered here (both the `pkg_resources.DistributionNotFound` errors and the `ImportError: numpy.core.multiarray failed to import` error) get fixed via hexrd/hexrd#183 and the changes I just pushed to #764.

**Comment by cjh1** [comment]
I will remove fabio from our channel gladly!

**Comment by joelvbernier** [comment]
What are the most current dev install insgtructions?  I tried 
```
conda install -c HEXRD -c anaconda -c conda-forge hexrdgui
CONDA_BUILD=1 pip install --no-deps -U -e hexrd
CONDA_BUILD=1 pip install --no-deps -U -e hexrdgui
``` 
and am still getting the fabio exception
```
pkg_resources.ContextualVersionConflict: (fabio 0.11.0a1 (/Users/bernier2/miniconda3/envs/hexrdgui/lib/python3.8/site-packages), Requirement.parse('fabio>=0.11'), {'hexrdgui'})
```

**Comment by psavery** [comment]
[This commit](https://github.com/HEXRD/hexrdgui/pull/764/commits/46990220a921861a9ed250f66c79825c34df5f9b) in #764 fixes the fabio issue. #764 is not yet merged into master.

I've also updated the [install instructions](https://github.com/HEXRD/hexrdgui/pull/764/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R65-R68) in #764 to show that these are the commands now:
```bash
conda install -c HEXRD -c anaconda -c conda-forge hexrdgui
CONDA_BUILD=1 pip install --no-build-isolation --no-deps -U -e hexrd
CONDA_BUILD=1 pip install --no-build-isolation --no-deps -U -e hexrdgui
```

Let me take a quick look at #764. I think after we clarify that python 3.8 is needed, it might be good to go.
